ci: Also check incidents-and-escalations for ci-regexp
Mainly motivated by
https://github.com/MaterializeInc/incidents-and-escalations/issues/72
which would have silenced the parallel workload failure here:
https://buildkite.com/materialize/nightly/builds/9405#0191bf60-478f-410d-bdba-693f97bee157

    parallel-workload-materialized-1     | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-038ffe6283a5930a9-1/materialize/test/src/persist-client/src/internal/state.rs:1472:17: LeasedReaderId(r7ef9c21d-4778-4cbb-b24b-6e5e1258754f) was expired due to inactivity. Did the machine go to sleep?