Sql: accurately reflect rolcanlogin, rolsuper, rolpassword in builtin tables (#33697)
We've had to limit access to pg_authid to superusers since it now
includes the password hash. This is potentially a breaking change for
some users but pg_roles has everything pg_authid does sans password.

This PR also introduces a new catalog table `mz_role_auth` which
reflects the hashes directly. It also requires superuser to access.

```
materialize=> select mz_is_superuser(); 
 mz_is_superuser 
-----------------
 t
(1 row)

materialize=> select * from pg_authid;
  oid  |       rolname       | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit |                                                                         rolpassword                                                                         | rolvaliduntil 
-------+---------------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------
 16662 | mz_support          | f        | t          | f             | f           | f           | f              | f            |           -1 |                                                                                                                                                             | 
 16663 | mz_monitor          | f        | t          | f             | f           | f           | f              | f            |           -1 |                                                                                                                                                             | 
 16984 | mz_analytics        | f        | t          | f             | f           | f           | f              | f            |           -1 |                                                                                                                                                             | 
 16664 | mz_monitor_redacted | f        | t          | f             | f           | f           | f              | f            |           -1 |                                                                                                                                                             | 
 20195 | foo                 | t        | t          | f             | f           | t           | f              | f            |           -1 | SCRAM-SHA-256$600000:Pb7u6iyRInqGiFMVHAaippAdJCAW1CfkO9Jq5nzGpeE=$EX69JKQgRJwEVegyKs2XGYEq/MzpGiNQlWSZCo2HCk4=:/zMJdohQrhCb995g+A+ghVapYoDP51ti3xpPPbqPCGg= | 
 16661 | mz_system           | t        | t          | t             | t           | t           | f              | f            |           -1 | SCRAM-SHA-256$600000:p4WSwV97is0cboeXkv5ZtB6B8qczWv05jZzOL5B61+I=$U9nWhjZp2KItA84sHmWZhzLx+977K4mmoalP85oUICU=:FOG72F2xcz70RIRzBqdvDvco6afr3aD37dEINqT/XYE= | 
 20000 | materialize         | f        | t          | t             | t           | t           | f              | f            |           -1 | SCRAM-SHA-256$600000:kStw6R10snsJEX3ubr1Sjt21QyGKWuV8WiS4EVfGUKg=$sMyGqAxbvuWPl25gZ3jJtkhfmpyd3927svzak9YcGBM=:IBwmkrKBxolG/Onpl1W4cXZT8Qb9xB7xkgBCueNo7qA= | 
(7 rows)

materialize=> select * from pg_roles;
       rolname       | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolconnlimit | rolpassword | rolvaliduntil | rolbypassrls | rolconfig |  oid  
---------------------+----------+------------+---------------+-------------+-------------+----------------+--------------+-------------+---------------+--------------+-----------+-------
 foo                 | t        | t          | f             | f           | t           | f              |           -1 | ********    |               | f            |           | 20195
 mz_system           | t        | t          | t             | t           | t           | f              |           -1 | ********    |               | f            |           | 16661
 mz_monitor          | f        | t          | f             | f           | f           | f              |           -1 | ********    |               | f            |           | 16663
 mz_support          | f        | t          | f             | f           | f           | f              |           -1 | ********    |               | f            |           | 16662
 materialize         | f        | t          | t             | t           | t           | f              |           -1 | ********    |               | f            |           | 20000
 mz_analytics        | f        | t          | f             | f           | f           | f              |           -1 | ********    |               | f            |           | 16984
 mz_monitor_redacted | f        | t          | f             | f           | f           | f              |           -1 | ********    |               | f            |           | 16664
(7 rows)
```

```
materialize=> select mz_is_superuser();
 mz_is_superuser 
-----------------
 f
(1 row)

materialize=> select * from pg_authid;
ERROR:  permission denied for VIEW "pg_catalog.pg_authid"
DETAIL:  The 'materialize' role needs SELECT privileges on VIEW "pg_catalog.pg_authid"
materialize=> 

```


<!--
Describe the contents of the PR briefly but completely.

If you write detailed commit messages, it is acceptable to copy/paste
them
here, or write "see commit messages for details." If there is only one
commit
in the PR, GitHub will have already added its commit message above.
-->

### Motivation

<!--
Which of the following best describes the motivation behind this PR?

  * This PR fixes a recognized bug.

    [Ensure issue is linked somewhere.]

  * This PR adds a known-desirable feature.

    [Ensure issue is linked somewhere.]

  * This PR fixes a previously unreported bug.

    [Describe the bug in detail, as if you were filing a bug report.]

  * This PR adds a feature that has not yet been specified.

[Write a brief specification for the feature, including justification
for its inclusion in Materialize, as if you were writing the original
     feature specification.]

   * This PR refactors existing code.

[Describe what was wrong with the existing code, if it is not obvious.]
-->

### Tips for reviewer

<!--
Leave some tips for your reviewer, like:

    * The diff is much smaller if viewed with whitespace hidden.
    * [Some function/module/file] deserves extra attention.
* [Some function/module/file] is pure code movement and only needs a
skim.

Delete this section if no tips.
-->

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly
considered. ([trigger-ci for additional test/nightly
runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design
doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md),
is a design doc
([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)),
or is sufficiently small to not require a design.
  <!-- Reference the design in the description. -->
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T`
mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md)
(possibly in a backwards-incompatible way), then it is tagged with a
`T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests,
there is a companion cloud PR to account for those changes that is
tagged with the release-blocker label
([example](https://github.com/MaterializeInc/cloud/pull/5021)).
<!-- Ask in #team-cloud on Slack if you need help preparing the cloud
PR. -->
- [ ] If this PR includes major [user-facing behavior
changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note),
I have pinged the relevant PM to schedule a changelog post.