build: Update crc32c version
Causes build failures in nightly: https://buildkite.com/materialize/nightly/builds/8208#01904b4d-44c4-48bb-909a-44a04fa26077

error[E0635]: unknown feature `stdarch_arm_crc32`
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/crc32c-0.6.5/src/lib.rs:23:60
   |
23 | #![cfg_attr(all(target_arch = "aarch64", nightly), feature(stdarch_arm_crc32))]
   |