sql: implement current_* system function aliases (#27171)
This PR implements the `current_catalog()`, `current_role()`, and
`user()` system information functions. ~~In addition, it also adds
support for the non-parenthesis versions of `current_database`,
`current_catalog`, and `user`, thus unifying how these functions can be
used.~~ Second part postponed because of #27228.

These are aliased as follows:
* current_catalog() -> current_database()
* current_role()/user() -> current_user()

* current_database/current_catalog -> current_database()
* user -> current_user()

Note that the docs
[state](https://materialize.com/docs/sql/functions/#system-information-func)
that `current_role()` is supported, however currently only the
non-parenthesis version is supported:
```bash
materialize=> select current_role;
 current_role 
--------------
 materialize
(1 row)

materialize=> select current_role();
ERROR:  function "current_role" does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
``` 

This PR also adds tests that ensure that all the aliases are mapped
correctly.

Fixes #22147
Fixes #22148

### Motivation

As per #18824, the current_* system information functions should be
allowed with and without parenthesis. The following table shows the
final state. This PR implements the `new` section, while the blanks ones
are already implemented.

|                  | keyword | function | aliased to       |
| ---------------- | ------- | -------- | ---------------- |
| current_catalog  | postponed     | new      | current_database |
| current_database | postponed     |          |                  |
| current_user     |         |          |                  |
| current_role     |         | new      | current_user     |
| user             | postponed     | new      | current_user     |
| current_schema   |         |          |                  |
| session_user   |         |          |                  |

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly
considered. ([trigger-ci for additional test/nightly
runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design
doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md),
is a design doc
([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)),
or is sufficiently small to not require a design.
  <!-- Reference the design in the description. -->
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T`
mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md)
(possibly in a backwards-incompatible way), then it is tagged with a
`T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests,
there is a companion cloud PR to account for those changes that is
tagged with the release-blocker label
([example](https://github.com/MaterializeInc/cloud/pull/5021)).
<!-- Ask in #team-cloud on Slack if you need help preparing the cloud
PR. -->
- [x] This PR includes the following [user-facing behavior
changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
- Add `current_catalog`, `current_role`, and `user` system information
functions.
- Ensure that the `current_catalog`, `current_database`, and `user`
system information functions can also be used without parenthesis.