sql: fix handling of `DROP CLUSTER REPLICA foo."bar-baz"`
Prior to this changes, this would fail:

```sql
materialize=> CREATE CLUSTER REPLICA default."test-123" SIZE '1';
CREATE CLUSTER REPLICA
materialize=> DROP CLUSTER REPLICA default."test-123";
ERROR:  CLUSTER default has no CLUSTER REPLICA named "test-123"
```

The reason was that we converted the replica name ident into a string by calling
`.to_string()`, which returns a quoted string when required by SQL, which in
turn makes the name lookup fail.