ci: Fix benchmark version overrides crudely
Caused by https://github.com/MaterializeInc/materialize/pull/34021

> builtins.AssertionError: Expected materialize/materialized:v0.164.0-dev.0--main.gc28d0061a6c9e63ee50a5f555c5d90373d006686 to be of profile RELEASE, but found OPTIMIZED instead. Consider passing `--release` or `--optimized` to `mzcompose` explicitly. Set CI_IGNORE_BUILD_PROFILE=1 if you don't care about comparability of benchmark results.

Seen in https://buildkite.com/materialize/nightly/builds/13985#019a53a4-7545-4043-8a33-7d85ad85023d

The root cause is that we now use LTO Release builds only for releases +
nightly, not for normal test runs. So the tagged runs from test pipeline
are all Optimized builds, comparing against them for performance doesn't
make sense.