Remove the old timestamp selection (#34712)
The first commit removes the old timestamp selection, as discussed here:
https://materializeinc.slack.com/archives/C08A62E0751/p1767794273757089?thread_ts=1764865885.225539&cid=C08A62E0751

The second commit updates a bunch of tests and fixes the error message
when we don't find a suitable timestamp: Both the old and the new
timestamp selection were relying on
`generate_timestamp_not_valid_error_msg`, but that doesn't work well for
the new timestamp selection for `AS OF` queries: the candidate comes out
not as the `AS OF` time, so
```
SELECT * FROM t AS OF 1
```
would regress from
```
Timestamp (1) is not valid for all inputs: [u1]
```
to
```
Timestamp (1768481949666) is not valid for all inputs: []
```
which does not make sense: The `[]` is the list of inputs that this
timestamp is not valid for, so we can see that actually this timestamp
is valid for all inputs. But the problem here is not that this timestamp
is not valid for an input, but the problem is the `AS OF`, which is not
mentioned by the error msg.

So, the PR makes the error message print the constraints instead. It
also tweaks the formatting of constraints a bit, to use more user-facing
terminology, e.g., instead of `ComputeInput` we now say `Indexed input`.
So, now we have stuff like:
```
select * from t AS OF 7;

ERROR:  could not find a valid timestamp for the query
DETAIL:  Constraints:
lower:
  (Storage inputs: [u1]): [1768492534743 (2026-01-15 15:55:34.743)]
upper:
  (Query's AS OF): [            7 (1970-01-01 00:00:00.007)]
```

~**Edit:** I'm still fighting with a lot of annoying test output
rewrites.~ **Edit 2:** Nightly is green.
https://buildkite.com/materialize/nightly/builds/14740