Improve aws error messaging  (#35613)
AWS provides a struct that makes their errors signficatly more readable:
https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/error/struct.DisplayErrorContext.html

Currently they are basically useless, looking like: 

```
Error: COPY FROM: error: parquet error: Parquet error: error: aws s3 request error: streaming error
causes: ["aws_s3"]
causes: ["parquet", "split", "fetch work", "decode chunk", "stage batches"]
```