ci: Parallelise platform-checks 0dt scenarios
Should unflake them: https://buildkite.com/materialize/nightly/builds/10187

thread 'timely:work-0' panicked at src/persist-client/src/internal/state.rs:1842:17: LeasedReaderId(r136e0830-75d8-4385-914c-cca1bc0e0f8b) was expired due to inactivity. Did the machine go to sleep?