console: fix image tags resolution for console sql tests and fix playwright scalability tests  (#37408)
Fix mzbuild double-prefixed image tags when MZ_GHCR is set so
materialized-base can resolve its locally built console and set
PLAYWRIGHT_FORCE_ASYNC_LOADER=1 for the e2e/scalability Playwright
scripts.

### Motivation

When trying to run `./mzcompose run default` I was seeing this error so
this should fix that unblock the console to run sql tests

`ERROR: failed to build: failed to solve:
ghcr.io/materializeinc/materialize/console:mzbuild-GS2MVTPNL2MPVZ5ZCKEL2MMBOFSXKT3Z:
failed to resolve source metadata for
ghcr.io/materializeinc/materialize/console:mzbuild-GS2MVTPNL2MPVZ5ZCKEL2MMBOFSXKT3Z:
ghcr.io/materializeinc/materialize/console:mzbuild-GS2MVTPNL2MPVZ5ZCKEL2MMBOFSXKT3Z:
not found
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
File
"/Users/qindeel/dev/materialize/misc/python/materialize/cli/mzcompose.py",
line 1074, in <module>
    main(sys.argv[1:])
File
"/Users/qindeel/dev/materialize/misc/python/materialize/cli/mzcompose.py",
line 179, in main
    args.command.invoke(args)
File
"/Users/qindeel/dev/materialize/misc/python/materialize/cli/mzcompose.py",
line 285, in invoke
    self.run(args)
File
"/Users/qindeel/dev/materialize/misc/python/materialize/cli/mzcompose.py",
line 808, in run
    super().run(args)
File
"/Users/qindeel/dev/materialize/misc/python/materialize/cli/mzcompose.py",
line 703, in run
    composition.dependencies.acquire()
File
"/Users/qindeel/dev/materialize/misc/python/materialize/mzbuild.py",
line 1424, in acquire
    dep.build(prep)
File
"/Users/qindeel/dev/materialize/misc/python/materialize/mzbuild.py",
line 1032, in build
    self._build_locked(prep, push)
File
"/Users/qindeel/dev/materialize/misc/python/materialize/mzbuild.py",
line 1109, in _build_locked
    spawn.runv(cmd, stdin=f, stdout=sys.stderr.buffer)
File "/Users/qindeel/dev/materialize/misc/python/materialize/spawn.py",
line 75, in runv
    return subprocess.run(
           ^^^^^^^^^^^^^^^
File
"/Users/qindeel/.pyenv/versions/3.12.1/lib/python3.12/subprocess.py",
line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'buildx', 'build',
'--progress=plain', '-f', '-', '--build-arg=BUILD_PROFILE=OPTIMIZED',
'--build-arg=ARCH_GCC=aarch64', '--build-arg=ARCH_GO=arm64',
'--build-arg=CI_SANITIZER=none', '-t',
'docker.io/ghcr.io/materializeinc/materialize/materialized-base:mzbuild-IIJEPWGM4KPJH6HMCMMMJDI76VPD3E7R',
'-t',
'ghcr.io/materializeinc/ghcr.io/materializeinc/materialize/materialized-base:mzbuild-IIJEPWGM4KPJH6HMCMMMJDI76VPD3E7R',
'--platform=linux/arm64',
'/Users/qindeel/dev/materialize/misc/images/materialized-base',
'--load']' returned non-zero exit status 1.`


### Verification

After this fix, image is pulled cleanly and yarn test:sql runs fine
locally