Disable mz-ore default features in mz-tls-util (#35879)
Disable mz-ore default features in mz-tls-util.

### Motivation
We use mz-tls-util in cloud, and the default feature was enabling
tokio-console in mz-ore, but not in mz-orchestrator-tracing. This caused
the struct to have different fields and fail compilation.
```
error[E0063]: missing field `tokio_console` in initializer of `TracingConfig<_>`
   --> vendor/materialize/src/orchestrator-tracing/src/lib.rs:272:36
    |
272 |         mz_ore::tracing::configure(TracingConfig {
    |                                    ^^^^^^^^^^^^^ missing `tokio_console`
```
### Verification

Running the tests.