Fix python type hint errors arising from numpy 1.24.2 update
As self._data is defined to be List[float], we can safely pass
dtype=float. Otherwise we'd have to cast to float after the function
call.

Sample error message:

misc/python/materialize/feature_benchmark/aggregation.py:46: error:
Incompatible types in assignment (expression has type "floating[Any]", variable
has type "float")  [assignment]
            stdev: float = np.std(self._data)
                           ^~~~~~~~~~~~~~~~~~