cloudtest: Update error message for privatelink connections
Follow-up to https://github.com/MaterializeInc/materialize/pull/33113

Failed in https://buildkite.com/materialize/nightly/builds/12753#019860f6-2585-4c08-b149-1372ff06c9e8

AssertionError: Regex pattern did not match.
 Regex: 'invalid CONNECTION: PORT in AWS PRIVATELINK is only supported for kafka'
 Input: "{'S': 'ERROR', 'C': 'XX000', 'M': 'invalid CONNECTION: POSTGRES does not support PORT for AWS PRIVATELINK'}"